/** Premade Party-mode prompts, offered as an alternative to writing a custom one. */
export const PARTY_PROMPTS: readonly string[] = [
  "When your best friend tells you good news",
  "The song that plays when you walk into a party",
  "Getting ready to go out with your friends",
  "3am on a road trip and everyone else is asleep",
  "The last song you'd want played at your funeral",
  "You just got dumped and you're not okay",
  "You just got dumped and you're thriving",
  "Sunday morning, coffee, no plans",
  "The gym playlist song that makes you feel unstoppable",
  "Slow dancing in the kitchen",
  "You're the main character walking down the street",
  "First day of summer",
  "The song your parents played on every car ride",
  "Songs that make you cry even though you don't know why",
  "You just won something you didn't expect to win",
  "The villain's entrance in a movie",
  "A song to fall asleep to",
  "You're about to do something you're nervous about",
  "The last song of the night at a wedding",
  "Driving nowhere in particular with the windows down",
  "A guilty pleasure you'd never admit to loving",
  "The song that reminds you of your first crush",
  "Studying for a test you should've started earlier",
  "You just reconciled with someone after a big fight",
  "The credits are rolling and the movie just ended you",
  "A song for staring out a rainy window",
  "You're cooking dinner alone and dancing badly",
  "The energy of your friend group's group chat",
  "A song that feels like a warm hug",
  "You're about to walk into a job interview",
  "The soundtrack to a breakup montage",
  "A song you'd play to introduce yourself to aliens",
  "Packing your bags for a trip you've been dreaming about",
  "The song that always gets skipped, but shouldn't",
  "You just aced something you were sure you'd fail",
  "A song for pretending you're in a music video",
  "The last text before you fell asleep on the phone",
  "Something to blast while cleaning your room",
  "A song that feels like nostalgia for a place you've never been",
  "You're the last one standing at the party",
  "The song stuck in your head for no reason",
  "A song for watching the sunset with someone you love",
  "You just found out plans got cancelled and you're relieved",
  "The one song you'd want on a deserted island",
  "A song that makes you want to run through an airport",
  "You're pretending to be fine but you're really not",
  "The soundtrack to getting revenge (the petty kind)",
  "A song for the version of you five years from now",
  "You just reunited with someone after years apart",
  "The song that plays right before the plot twist",
];
